apiVersion: apps/v1
kind: Deployment
metadata:
  name: app_ef
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app_ef
  template:
    metadata:
      labels:
        app: app_ef
    spec:
      containers:
        - name: app_ef
          image: wil42/playground:v1
          ports:
            - containerPort: 80
